/*
$Header: d:/tads/lib/RCS/los.h 1.2 96/10/14 15:54:43 mroberts Exp Locker: mroberts $
*/

/* Copyright (c) 1991 by Michael J. Roberts.  All Rights Reserved. */
/*
Name
  los.h - library operating system definitions
Function
  Definitions that vary by operating system
Notes
  None
Modified
  01/08/93 SMcAdams  - add OSMAXINT, OSMAXUINT for DOS
  12/30/92 MJRoberts - created from TADS os.h
  08/13/91 MJRoberts - creation
*/

#ifndef LOS_INCLUDED
#define LOS_INCLUDED

#include "os.h"

#endif /* LOS_INCLUDED */
