/*
$Header: c:/tads/tads2/RCS/PLY.H 1.3 92/11/24 21:57:16 mroberts Exp $
*/

/* Copyright (c) 1992 by Michael J. Roberts.  All Rights Reserved. */
/*
Name
  ply.h - definitions for game play loop
Function
  definitions for game play loop
Notes
  none
Modified
  04/11/92 MJRoberts     - creation
*/

#ifndef PLY_INCLUDED
#define PLY_INCLUDED

void plygo(/*_ struct runcxdef *run, struct voccxdef *voc,
               struct tiocxdef *tio, objnum preinit, int inited _*/);

#endif /* PLY_INCLUDED */
