/*
$Header: c:/tads/tads2/RCS/std.h 1.5 93/01/08 04:35:01 mroberts Exp $
*/

/* Copyright (c) 1991 by Michael J. Roberts.  All Rights Reserved. */
/*
Name
  std.h - standard definitions
Function
  Various standard definitions
Notes
  None
Modified
  12/30/92 MJRoberts     - adjusted to use lib.h
  08/03/91 MJRoberts     - creation
*/

#ifndef STD_INCLUDED
#define STD_INCLUDED

/* pick up definitions from central library header */
#ifndef LIB_INCLUDED
# include "lib.h"
#endif

#ifndef OS_INCLUDED
# include "os.h"
#endif

#endif /* STD_INCLUDED */
